name: Test and Run Podman

on:
  push:
    branches: "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run:
          apt-get update -y
          apt-get install -y podman

      - name: Build image
        run:
          podman build . --tag github-ci-test
      
      - name: Run image
        run:
          podman run --rm --rmi github-ci-test
      

        
